[2023-03-14T22:41:58.694+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:41:58.702+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:41:58.702+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:41:58.703+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 3
[2023-03-14T22:41:58.703+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:41:58.712+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): JsonToCSV> on 2023-03-14 22:41:08.560415+00:00
[2023-03-14T22:41:58.718+0000] {standard_task_runner.py:55} INFO - Started process 207 to run task
[2023-03-14T22:41:58.723+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'JsonToCSV', 'manual__2023-03-14T22:41:08.560415+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp5aab0ws1']
[2023-03-14T22:41:58.724+0000] {standard_task_runner.py:83} INFO - Job 622: Subtask JsonToCSV
[2023-03-14T22:41:58.807+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [running]> on host 9cebcb3c5b96
[2023-03-14T22:41:59.167+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=JsonToCSV
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T22:41:08.560415+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T22:41:08.560415+00:00
[2023-03-14T22:41:59.187+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-03-14T22:41:59.189+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-03-14T22:41:59.484+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 28, in json_to_csv
    hook.invoke_lambda(function_name="json_to_csv",payload=pay_load)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 74, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 609, in conn
    return self.get_client_type(region_name=self.region_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 578, in get_client_type
    verify=self.verify,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 167, in create_client
    partition_data,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 497, in _get_client_args
    partition_data,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/args.py", line 99, in get_client_args
    scoped_config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/args.py", line 211, in compute_client_args
    s3_config=s3_config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/args.py", line 313, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/args.py", line 419, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 594, in resolve
    use_fips_endpoint=use_fips_endpoint,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/regions.py", line 234, in construct_endpoint
    use_fips_endpoint,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2023-03-14T22:41:59.496+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=JsonToCSV, execution_date=20230314T224108, start_date=20230314T224158, end_date=20230314T224159
[2023-03-14T22:41:59.504+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 622 for task JsonToCSV (You must specify a region.; 207)
[2023-03-14T22:41:59.539+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T22:41:59.559+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
