[2023-03-14T00:10:48.330+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [queued]>
[2023-03-14T00:10:48.335+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [queued]>
[2023-03-14T00:10:48.335+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T00:10:48.336+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 3
[2023-03-14T00:10:48.336+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T00:10:48.343+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): TestS3Hook> on 2023-03-14 00:09:25.066398+00:00
[2023-03-14T00:10:48.348+0000] {standard_task_runner.py:55} INFO - Started process 6739 to run task
[2023-03-14T00:10:48.351+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'TestS3Hook', 'manual__2023-03-14T00:09:25.066398+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpx5ouu9e3']
[2023-03-14T00:10:48.352+0000] {standard_task_runner.py:83} INFO - Job 311: Subtask TestS3Hook
[2023-03-14T00:10:48.395+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [running]> on host 4d2033ffb16b
[2023-03-14T00:10:48.559+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=TestS3Hook
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T00:09:25.066398+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T00:09:25.066398+00:00
[2023-03-14T00:10:48.561+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 7, in load_tables
    print("Working" + filename + key, + bucket_name)
TypeError: bad operand type for unary +: 'str'
[2023-03-14T00:10:48.569+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=TestS3Hook, execution_date=20230314T000925, start_date=20230314T001048, end_date=20230314T001048
[2023-03-14T00:10:48.575+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 311 for task TestS3Hook (bad operand type for unary +: 'str'; 6739)
[2023-03-14T00:10:48.611+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T00:10:48.624+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
