[2023-03-16T05:01:08.796+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetAudioQuality manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T05:01:08.802+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetAudioQuality manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T05:01:08.802+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T05:01:08.803+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 7
[2023-03-16T05:01:08.803+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T05:01:08.810+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): GetAudioQuality> on 2023-03-16 04:25:58.412323+00:00
[2023-03-16T05:01:08.815+0000] {standard_task_runner.py:55} INFO - Started process 8331 to run task
[2023-03-16T05:01:08.818+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'GetAudioQuality', 'manual__2023-03-16T04:25:58.412323+00:00', '--job-id', '1157', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpmkt0eggt']
[2023-03-16T05:01:08.819+0000] {standard_task_runner.py:83} INFO - Job 1157: Subtask GetAudioQuality
[2023-03-16T05:01:08.867+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.GetAudioQuality manual__2023-03-16T04:25:58.412323+00:00 [running]> on host 18c42e4ef76b
[2023-03-16T05:01:09.128+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=GetAudioQuality
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T04:25:58.412323+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T04:25:58.412323+00:00
[2023-03-16T05:02:06.413+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/extract.py", line 173, in get_song_audio_quality
    ti.xcom_push(key='audio_df',value=audio_df.to_json())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 211, in set
    raise ValueError(f"DAG run not found on DAG {dag_id!r} with ID {run_id!r}")
ValueError: DAG run not found on DAG 'Spotify_Data_ETL' with ID 'manual__2023-03-16T04:25:58.412323+00:00'
[2023-03-16T05:02:06.423+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=GetAudioQuality, execution_date=20230316T042558, start_date=20230316T050108, end_date=20230316T050206
[2023-03-16T05:02:06.432+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1157 for task GetAudioQuality ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(Spotify_Data_ETL, GetAudioQuality, manual__2023-03-16T04:25:58.412323+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'GetAudioQuality', 'dag_id': 'Spotify_Data_ETL', 'run_id': 'manual__2023-03-16T04:25:58.412323+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 3, 16, 5, 1, 8, 798120, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 3, 16, 5, 2, 6, 423306, tzinfo=Timezone('UTC')), 'duration': 57}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 8331)
[2023-03-16T05:02:06.469+0000] {local_task_job.py:208} INFO - Task exited with return code 1
