[2023-03-15T22:27:18.119+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-15T22:27:18.124+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-15T22:27:18.124+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T22:27:18.124+0000] {taskinstance.py:1280} INFO - Starting attempt 19 of 21
[2023-03-15T22:27:18.125+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T22:27:18.132+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): TransformData> on 2023-03-14 22:41:08.560415+00:00
[2023-03-15T22:27:18.137+0000] {standard_task_runner.py:55} INFO - Started process 14106 to run task
[2023-03-15T22:27:18.141+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'TransformData', 'manual__2023-03-14T22:41:08.560415+00:00', '--job-id', '798', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpbl8_58fm']
[2023-03-15T22:27:18.142+0000] {standard_task_runner.py:83} INFO - Job 798: Subtask TransformData
[2023-03-15T22:27:18.188+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-14T22:41:08.560415+00:00 [running]> on host af46459234d2
[2023-03-15T22:27:18.357+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=TransformData
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T22:41:08.560415+00:00
AIRFLOW_CTX_TRY_NUMBER=19
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T22:41:08.560415+00:00
[2023-03-15T22:27:18.388+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 28, in transform_data
    today = datetime.today().strftime('%Y-%m-%d')
AttributeError: module 'datetime' has no attribute 'today'
[2023-03-15T22:27:18.395+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=TransformData, execution_date=20230314T224108, start_date=20230315T222718, end_date=20230315T222718
[2023-03-15T22:27:18.402+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 798 for task TransformData (module 'datetime' has no attribute 'today'; 14106)
[2023-03-15T22:27:18.438+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-15T22:27:18.455+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
