[2023-03-21T03:00:42.025+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spotify_Data_ETL.load_csv manual__2023-03-21T03:00:40.656791+00:00 [queued]>
[2023-03-21T03:00:42.030+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spotify_Data_ETL.load_csv manual__2023-03-21T03:00:40.656791+00:00 [queued]>
[2023-03-21T03:00:42.030+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T03:00:42.031+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 3
[2023-03-21T03:00:42.031+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T03:00:42.039+0000] {taskinstance.py:1303} INFO - Executing <Task(S3ToSnowflakeOperator): load_csv> on 2023-03-21 03:00:40.656791+00:00
[2023-03-21T03:00:42.045+0000] {standard_task_runner.py:55} INFO - Started process 19849 to run task
[2023-03-21T03:00:42.050+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'load_csv', 'manual__2023-03-21T03:00:40.656791+00:00', '--job-id', '1710', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp6o5059ue']
[2023-03-21T03:00:42.051+0000] {standard_task_runner.py:83} INFO - Job 1710: Subtask load_csv
[2023-03-21T03:00:42.111+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.load_csv manual__2023-03-21T03:00:40.656791+00:00 [running]> on host 1fd7b08731f2
[2023-03-21T03:00:42.163+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:00:40.656791+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T03:00:40.656791+00:00
[2023-03-21T03:00:42.164+0000] {s3_to_snowflake.py:146} INFO - Executing COPY command...
[2023-03-21T03:00:42.180+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/transfers/s3_to_snowflake.py", line 147, in execute
    snowflake_hook.run(copy_query, self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 373, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 295, in get_conn
    conn_config = self._get_conn_params()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 208, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2023-03-21T03:00:42.183+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=load_csv, execution_date=20230321T030040, start_date=20230321T030042, end_date=20230321T030042
[2023-03-21T03:00:42.190+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1710 for task load_csv (The conn_id `snowflake_default` isn't defined; 19849)
[2023-03-21T03:00:42.220+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T03:00:42.237+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
