[2023-03-11T23:21:06.233+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:21:03.414733+00:00 [queued]>
[2023-03-11T23:21:06.237+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:21:03.414733+00:00 [queued]>
[2023-03-11T23:21:06.238+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T23:21:06.238+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-03-11T23:21:06.239+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T23:21:06.245+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): GetSongsFromPlaylist> on 2023-03-11 23:21:03.414733+00:00
[2023-03-11T23:21:06.249+0000] {standard_task_runner.py:55} INFO - Started process 447 to run task
[2023-03-11T23:21:06.253+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'GetSongsFromPlaylist', 'manual__2023-03-11T23:21:03.414733+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpukqrf5k6']
[2023-03-11T23:21:06.253+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask GetSongsFromPlaylist
[2023-03-11T23:21:06.299+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.GetSongsFromPlaylist manual__2023-03-11T23:21:03.414733+00:00 [running]> on host 4fa3b0adb91e
[2023-03-11T23:21:06.342+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=GetSongsFromPlaylist
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T23:21:03.414733+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-11T23:21:03.414733+00:00
[2023-03-11T23:21:06.430+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/extract.py", line 60, in get_songs_from_playlist
    for item in r['items']:
KeyError: 'items'
[2023-03-11T23:21:06.439+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=GetSongsFromPlaylist, execution_date=20230311T232103, start_date=20230311T232106, end_date=20230311T232106
[2023-03-11T23:21:06.447+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task GetSongsFromPlaylist ('items'; 447)
[2023-03-11T23:21:06.464+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-11T23:21:06.477+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
