[2023-03-21T22:47:48.263+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spotify_Data_ETL.insert_date manual__2023-03-21T22:47:20.265233+00:00 [queued]>
[2023-03-21T22:47:48.269+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spotify_Data_ETL.insert_date manual__2023-03-21T22:47:20.265233+00:00 [queued]>
[2023-03-21T22:47:48.269+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T22:47:48.270+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 3
[2023-03-21T22:47:48.270+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T22:47:48.277+0000] {taskinstance.py:1303} INFO - Executing <Task(SnowflakeOperator): insert_date> on 2023-03-21 22:47:20.265233+00:00
[2023-03-21T22:47:48.282+0000] {standard_task_runner.py:55} INFO - Started process 21772 to run task
[2023-03-21T22:47:48.286+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'insert_date', 'manual__2023-03-21T22:47:20.265233+00:00', '--job-id', '2256', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmp2ienpoyt']
[2023-03-21T22:47:48.286+0000] {standard_task_runner.py:83} INFO - Job 2256: Subtask insert_date
[2023-03-21T22:47:48.333+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.insert_date manual__2023-03-21T22:47:20.265233+00:00 [running]> on host 1fd7b08731f2
[2023-03-21T22:47:48.376+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=insert_date
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T22:47:20.265233+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T22:47:20.265233+00:00
[2023-03-21T22:47:48.377+0000] {sql.py:254} INFO - Executing: 
    INSERT INTO calendar_dim (date, month, month_name,day_of_month,day_of_week,day_name,quarter)
    VALUES (2023-03-21, 3, March,21,1,Tuesday,1)
    
[2023-03-21T22:47:48.386+0000] {base.py:73} INFO - Using connection ID 'snowflake_connection' for task execution.
[2023-03-21T22:47:48.486+0000] {base.py:73} INFO - Using connection ID 'snowflake_connection' for task execution.
[2023-03-21T22:47:48.489+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.49-linuxkit-aarch64-with-debian-11.6
[2023-03-21T22:47:48.490+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-21T22:47:48.490+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-21T22:47:48.975+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-21T22:47:49.056+0000] {cursor.py:751} INFO - query execution done
[2023-03-21T22:47:49.060+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-21T22:47:49.062+0000] {sql.py:375} INFO - Running statement: INSERT INTO calendar_dim (date, month, month_name,day_of_month,day_of_week,day_name,quarter)
    VALUES (2023-03-21, 3, March,21,1,Tuesday,1), parameters: None
[2023-03-21T22:47:49.063+0000] {cursor.py:738} INFO - query: [INSERT INTO calendar_dim (date, month, month_name,day_of_month,day_of_week,day_n...]
[2023-03-21T22:47:49.172+0000] {cursor.py:751} INFO - query execution done
[2023-03-21T22:47:49.185+0000] {connection.py:586} INFO - closed
[2023-03-21T22:47:49.245+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-21T22:47:49.315+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01ab1a77-0004-610c-0000-00552087d181: SQL compilation error: error line 2 at position 27
invalid identifier 'MARCH'
[2023-03-21T22:47:49.328+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=insert_date, execution_date=20230321T224720, start_date=20230321T224748, end_date=20230321T224749
[2023-03-21T22:47:49.343+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2256 for task insert_date (000904 (42000): 01ab1a77-0004-610c-0000-00552087d181: SQL compilation error: error line 2 at position 27
invalid identifier 'MARCH'; 21772)
[2023-03-21T22:47:49.404+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T22:47:49.426+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
